"""Added columns

Revision ID: 7cbddf10b495
Revises: 06ed97e5c7f1
Create Date: 2020-06-03 19:56:43.638156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbddf10b495'
down_revision = '06ed97e5c7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
